# Generated by Django 2.1 on 2021-01-20 08:04

from django.db import migrations, models
import django.db.models.deletion
import utils.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=32, verbose_name='SMTP服务器')),
                ('email_port', models.IntegerField(verbose_name='SMTP端口')),
                ('email_user', models.EmailField(max_length=128, verbose_name='邮箱帐号')),
                ('email_password', models.CharField(max_length=32, verbose_name='邮箱密码')),
            ],
            options={
                'verbose_name': '发件邮箱设置',
                'verbose_name_plural': '发件邮箱设置',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=utils.util.FileStorage(), upload_to='upload/')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.FloatField(verbose_name='编号')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='菜单名')),
                ('code', models.CharField(max_length=64, verbose_name='编码')),
                ('url', models.CharField(max_length=128, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['sort_number'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.FloatField(verbose_name='编号')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(blank=True, to='system.Menu', verbose_name='URL授权')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['sort_number'],
            },
        ),
    ]
