# Generated by Django 2.1 on 2021-01-20 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=32, unique=True, verbose_name='单号')),
                ('content', models.TextField(max_length=512, verbose_name='内容')),
                ('state', models.CharField(blank=True, choices=[('wait', '等待处理'), ('process', '正在处理'), ('finish', '处理完毕'), ('confirm', '确认完成')], default='wait', max_length=16, verbose_name='状态')),
                ('type', models.CharField(choices=[('normal', '普通问题'), ('email', '邮件问题'), ('erp', 'ERP问题'), ('print', '打印问题'), ('transmission', '上传下载')], default='normal', max_length=16, verbose_name='类型')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '日常工单',
                'verbose_name_plural': '日常工单',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('process', '处理'), ('finish', '完成'), ('confirm', '确认')], max_length=16, verbose_name='记录类型')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('record_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worktable.WorkOrder', verbose_name='单号')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_recorder', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '日常工单记录',
                'verbose_name_plural': '日常工单记录',
            },
        ),
    ]
