"""
Django settings for MIS project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from os import path as os_path
from sys import path as sys_path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os_path.dirname(os_path.dirname(os_path.abspath(__file__)))
sys_path.insert(0, os_path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k5j11+o9v_+%@q(sirty#&u8tav3x+tcbdy4t4zv3%saasuw*q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.UserProfile'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'apps.system.apps.SystemConfig',
    'apps.users.apps.UsersConfig',
    'apps.asset.apps.AssetConfig',
    'apps.worktable.apps.WorkTableConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.utils.middleware.MenuCollection',
    'apps.utils.middleware.ActionMiddleware',
    # 'apps.utils.middleware.RbacMiddleware',
]

ROOT_URLCONF = 'MIS.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os_path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.utils.global_params.previous_page',
            ],
        },
    },
]

WSGI_APPLICATION = 'MIS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'MIS',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': 'hondabus',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [os_path.join(BASE_DIR, 'static')]


MEDIA_URL = '/media/'

MEDIA_ROOT = os_path.join(BASE_DIR, 'media')

LOGIN_URL = '/login/'

# safe url
SAFE_URL = [r'^/$',
            '/login/',
            '/logout',
            '/index/',
            '/media/',
            '/admin/',
            ]

"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # email後端
EMAIL_USE_TLS = False   # 是否使用TLS安全傳輸協議
EMAIL_USE_SSL = True    # 是否使用SSL加密，qq企業郵箱要求使用
EMAIL_HOST = 'smtp.exmail.qq.com'   # 發送郵件的郵箱 的 SMTP伺服器
EMAIL_PORT = 465     # 發件箱的SMTP伺服器端口
EMAIL_HOST_USER = 'robot@qsmfg.com'    # 發送郵件的郵箱地址
EMAIL_HOST_PASSWORD = 'Ewig@2020'         # 發送郵件的郵箱密碼
"""

REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication',),
    'DATETIME_FORMAT': "%Y-%m-%d %H:%M",
    'DEFAULT_PAGINATION_CLASS': 'apps.utils.pagination.CommonPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}
